"""Trusted, offline disposable-session fixture; never used as a production backend.

The native session/track template is first generated by Ardour. A test source and
region are added before the GUI opens it, allowing audio-edit bindings to be tested
without enabling an unverified production import tool. Numeric time strings are
the sample representation accepted by Temporal's backward-compatible XML parser.
"""

import math
import struct
import wave
from pathlib import Path
from xml.etree import ElementTree as ET


def add_audio_fixture(session: Path, wav: Path) -> None:
    with wave.open(str(wav), "wb") as stream:
        stream.setparams((1, 2, 48000, 48000, "NONE", "not compressed"))
        stream.writeframes(
            b"".join(
                struct.pack("<h", round(32767 * 0.1 * math.sin(2 * math.pi * 600 * i / 48000)))
                for i in range(48000)
            )
        )
    document = ET.parse(session)
    root = document.getroot()
    sources = root.find("Sources")
    playlist = root.find("./Playlists/Playlist[@name='Audio Fixture.1']")
    assert sources is not None and playlist is not None
    root.set("id-counter", "700010")
    ET.SubElement(
        sources, "Source", {"id": "700001", "name": str(wav), "type": "audio", "channel": "0"}
    )
    ET.SubElement(
        playlist,
        "Region",
        {
            "id": "700002",
            "name": "Audio fixture",
            "type": "audio",
            "channels": "1",
            "source-0": "700001",
            "master-source-0": "700001",
            "start": "0",
            "position": "0",
            "length": "48000",
            "scale-amplitude": "1",
            "whole-file": "0",
            "muted": "0",
            "locked": "0",
        },
    )
    document.write(session, encoding="utf-8", xml_declaration=True)
