"""Generate tool reference and machine-readable schemas from registered typed specs."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from ardour_ultra_mcp.models.base import Result
from ardour_ultra_mcp.services.catalog import SPECS, UNSUPPORTED


def render() -> tuple[str, str]:
    lines = [
        "# Tool reference",
        "",
        "Generated by `python scripts/generate_reference.py`. Do not edit by hand.",
        "",
        "MCP tools accept a typed `request` object. All requests reject unknown fields and include optional `dry_run`, `expected_revision`, and `confirm_delete`. Results use the shared schema below; availability depends on the backend. A registered tool is not proof of a runtime capability.",
        "",
        "Collections default to 100 items and cap pages at 1,000. MIDI/automation batches cap at 10,000; control transactions at 100. Positions discriminate samples, seconds, quarter ticks (1920/quarter), or BBT. Pan is signed normalized -1..+1; gain is dB; plugin values explicitly use `plugin_native` unless a trustworthy physical unit is exposed.",
        "",
        "## Result schema",
        "",
        "```json",
        json.dumps(Result.model_json_schema(), indent=2),
        "```",
        "",
    ]
    schemas = {"result": Result.model_json_schema(), "tools": {}}
    category = None
    for spec in SPECS:
        if spec.category != category:
            category = spec.category
            lines += [f"## {category}", ""]
        schema = spec.request.model_json_schema()
        schemas["tools"][spec.name] = {
            "description": spec.description,
            "category": spec.category,
            "mutates": spec.mutates,
            "destructive": spec.destructive,
            "request_schema": schema,
        }
        lines += [
            f"### `{spec.name}`",
            "",
            spec.description,
            "",
            f"Mutation: `{spec.mutates}`. Explicit destructive intent: `{spec.destructive}`. Returns: `Result` (structured MCP output plus `isError` on failure).",
            "",
            "```json",
            json.dumps(schema, indent=2),
            "```",
            "",
            "Errors: typed `VALIDATION_ERROR`, `OBJECT_NOT_FOUND`, `CONFLICT`, `STALE_OBJECT`, backend availability/errors, and `OUTCOME_UNCERTAIN` where a published mutation cannot be confirmed. Exact enum is in Result schema.",
            "",
        ]
    lines += (
        ["## Unsupported adapters", "", "| Feature | Reason |", "|---|---|"]
        + [f"| {name} | {reason} |" for name, reason in UNSUPPORTED.items()]
        + [
            "",
            'Examples: [MIDI](MIDI.md), [plugins](PLUGINS.md), [automation](AUTOMATION.md), [routing](ROUTING.md), [quick start](QUICK_START.md). Each example must be wrapped as `{ "request": ... }` for an MCP tool call.',
            "",
        ]
    )
    return "\n".join(lines), json.dumps(schemas, indent=2) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    for path, value in zip(
        [Path("docs/TOOL_REFERENCE.md"), Path("docs/tool-schemas.json")], render(), strict=True
    ):
        if args.check:
            if not path.exists() or path.read_text() != value:
                raise SystemExit(f"Stale generated reference: {path}")
        else:
            path.write_text(value)


if __name__ == "__main__":
    main()
